# Generated by Django 3.2.20 on 2023-09-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetail',
            name='stafftype',
            field=models.CharField(default='Teaching Staff', max_length=10),
        ),
    ]
