# Generated by Django 3.2.20 on 2023-10-21 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EMS', '0002_employeedetail_stafftype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetail',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='employeedetail',
            name='desg',
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='DOB',
            field=models.DateField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='adhar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='altemail',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='altmob',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='bloodgroup',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='curcity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='curdist',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='curhousenum',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='curstate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='curstreet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='curzip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='mob',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='mstatus',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='pan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='presentcity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='presentdist',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='presenthousenum',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='presentstate',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='presentstreet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='presentzip',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='workexperience',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeedetail',
            name='worklocation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='NonTeachingEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50, null=True)),
                ('noe10', models.CharField(max_length=50, null=True)),
                ('board10', models.CharField(max_length=50, null=True)),
                ('marks10', models.IntegerField(default=0)),
                ('yop10', models.DateField(max_length=50, null=True)),
                ('noe12', models.CharField(max_length=50, null=True)),
                ('board12', models.CharField(max_length=50, null=True)),
                ('marks12', models.IntegerField(default=0)),
                ('yop12', models.DateField(max_length=50, null=True)),
                ('noedegree', models.CharField(max_length=50, null=True)),
                ('uni', models.CharField(max_length=50, null=True)),
                ('marksdeg', models.IntegerField(default=0)),
                ('yopdeg', models.DateField(max_length=50, null=True)),
                ('desg', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
