# Generated by Django 3.2.20 on 2023-10-27 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EMS', '0003_auto_20231021_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=50, null=True)),
                ('noe10', models.CharField(max_length=50, null=True)),
                ('board10', models.CharField(max_length=50, null=True)),
                ('marks10', models.IntegerField(default=0)),
                ('yop10', models.DateField(max_length=50, null=True)),
                ('noe12', models.CharField(max_length=50, null=True)),
                ('board12', models.CharField(max_length=50, null=True)),
                ('marks12', models.IntegerField(default=0)),
                ('yop12', models.DateField(max_length=50, null=True)),
                ('noedegree', models.CharField(max_length=50, null=True)),
                ('uni', models.CharField(max_length=50, null=True)),
                ('marksdeg', models.IntegerField(default=0)),
                ('yopdeg', models.DateField(max_length=50, null=True)),
                ('npg', models.CharField(max_length=50, null=True)),
                ('unipg', models.CharField(max_length=50, null=True)),
                ('markspg', models.IntegerField(default=0)),
                ('yoppg', models.DateField(max_length=50, null=True)),
                ('unidoc', models.CharField(max_length=50, null=True)),
                ('stramdoc', models.CharField(max_length=50, null=True)),
                ('dreg', models.DateField(max_length=50, null=True)),
                ('yopdoc', models.DateField(max_length=50, null=True)),
                ('unipdoc', models.CharField(max_length=50, null=True)),
                ('strampdoc', models.CharField(max_length=50, null=True)),
                ('stdate', models.DateField(max_length=50, null=True)),
                ('enddate', models.DateField(max_length=50, null=True)),
                ('desg', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
